import type { Patient } from "@/lib/sonoflow-types";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

export async function downloadElementAsPdf(elementId: string, filename: string) {
  const element = document.getElementById(elementId);
  if (!element) throw new Error("Element not found");

  const canvas = await html2canvas(element, {
    scale: 1.5, // Reduced from 2.0 to balance quality and size
    useCORS: true,
    logging: false,
    backgroundColor: "#ffffff"
  });

  // Use JPEG instead of PNG for significantly smaller file size
  const imgData = canvas.toDataURL("image/jpeg", 0.75); // 0.75 quality is usually plenty for text
  
  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
    compress: true // Enable internal PDF compression
  });

  const imgProps = pdf.getImageProperties(imgData);
  const pdfWidth = pdf.internal.pageSize.getWidth();
  const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;

  pdf.addImage(imgData, "JPEG", 0, 0, pdfWidth, pdfHeight, undefined, "FAST");
  pdf.save(`${filename}.pdf`);
}

export function exportReportToPdf(params: {
  patient: Patient;
  accession: string;
  exam: string;
  reportText: string;
  signedBy?: string | null;
  signedAt?: string | null;
}) {
  const printWindow = window.open("", "_blank", "noopener,noreferrer,width=900,height=1100");
  if (!printWindow) {
    throw new Error("Popup blocked. Allow popups to export PDF.");
  }

  const safeText = params.reportText
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  printWindow.document.write(`
    <!doctype html>
    <html>
      <head>
        <title>Sonolynx Report ${params.accession}</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 40px; color: #111827; }
          h1 { font-size: 20px; margin: 0 0 4px; }
          h2 { font-size: 13px; margin: 24px 0 8px; letter-spacing: 0.08em; text-transform: uppercase; color: #1d4ed8; }
          .meta { display: grid; grid-template-columns: 1fr 1fr; gap: 6px 24px; margin-top: 20px; font-size: 12px; }
          .report { margin-top: 28px; white-space: pre-wrap; font-family: "Courier New", monospace; font-size: 12px; line-height: 1.55; }
          .footer { margin-top: 32px; font-size: 11px; color: #4b5563; }
          @media print { button { display: none; } body { margin: 28px; } }
        </style>
      </head>
      <body>
        <button onclick="window.print()" style="float:right;padding:8px 12px;">Print / Save PDF</button>
        <h1>Sonolynx Radiology</h1>
        <div>Signed Ultrasound Report</div>
        <div class="meta">
          <div><strong>Patient:</strong> ${params.patient.lastName}, ${params.patient.firstName}</div>
          <div><strong>MRN:</strong> ${params.patient.mrn}</div>
          <div><strong>DOB:</strong> ${params.patient.dob}</div>
          <div><strong>Exam:</strong> ${params.exam}</div>
          <div><strong>Accession:</strong> ${params.accession}</div>
          <div><strong>Signed At:</strong> ${params.signedAt ?? "Pending"}</div>
          <div><strong>Signed By:</strong> ${params.signedBy ?? "Pending"}</div>
        </div>
        <h2>Report</h2>
        <div class="report">${safeText}</div>
        <div class="footer">Electronically generated by Sonolynx. Final clinical correlation required.</div>
      </body>
    </html>
  `);
  printWindow.document.close();
  printWindow.focus();
}

