# fly.toml app configuration file generated for sonolynx-radiology on 2026-05-09T21:43:52+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sonolynx-app'
primary_region = 'bom'

[build]
  [build.args]
    NEXT_PUBLIC_SUPABASE_URL = "https://mbskxsigmaduwywvluin.supabase.co"
    NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ic2t4c2lnbWFkdXd5d3ZsdWluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgwODc5MDUsImV4cCI6MjA5MzY2MzkwNX0.Cje5YagLV9zA2qpYaLxU5AqgGNfwTpNnpeaR7qSk8dI"
    NEXT_PUBLIC_DICOMWEB_API_URL = "https://d157502i736183.cloudfront.net/dicomweb"
    NEXT_PUBLIC_HL7_EXPORT_API_URL = "https://hl7-gateway.soulflow.ai/api/oru"
    NEXT_PUBLIC_REPORT_API_URL = "https://ai-report.soulflow.ai/api/generate"

[env]
  OPENAI_MODEL = "gpt-4o-mini"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
