$out = "C:\Users\USER\Documents\Codex\2026-05-06\can-u-access-my-github\SonuLab-React-Nextjs\SOFTWARE_CHANGELOG_2026-05-06.docx"
$tmp = Join-Path $env:TEMP ("docxgen_" + [guid]::NewGuid().ToString())

New-Item -ItemType Directory -Path $tmp | Out-Null
New-Item -ItemType Directory -Path (Join-Path $tmp "_rels") | Out-Null
New-Item -ItemType Directory -Path (Join-Path $tmp "word") | Out-Null

$contentTypes = @'
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>
'@

$rels = @'
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>
'@

$lines = @(
  "SonuLab React/Nextjs - Software Change Log",
  ("Generated on: " + (Get-Date -Format "yyyy-MM-dd HH:mm:ss")),
  "",
  "1) Repository and environment setup",
  "- Cloned repository and installed dependencies.",
  "- Resolved local PowerShell npm wrapper issue by using npm.cmd commands.",
  "- Started and verified local dev server on http://localhost:3000.",
  "",
  "2) Authentication and data access checks",
  "- Verified login is Supabase email/password based (no hardcoded password in UI code).",
  "- Queried configured Supabase project with anon key and confirmed key tables were empty in visible scope.",
  "- Confirmed no seeded default auth user credentials were present in migrations.",
  "",
  "3) Worksheet expansion for sonographer-required options",
  "- Expanded Abdomen worksheet model and UI fields: liver surface, kidney cortical echogenicity/stones, spleen echotexture, pancreas, vessels, ascites.",
  "- Expanded Thyroid worksheet model and UI fields: gland parenchyma/vascularity/nodes and rich nodule descriptors.",
  "",
  "4) Findings and impression rule updates",
  "- Reworked findings engine to include new abdomen and thyroid fields.",
  "- Added threshold-driven logic for key measurements and abnormality conditions.",
  "- Added recommendations section support to report output.",
  "",
  "5) Validation and safety controls",
  "- Added validation issue model (error/warning) with worksheet validators for abdomen and thyroid.",
  "- Added sign-off guardrails: block transmission when critical errors exist.",
  "- Added quality warnings in preview.",
  "- Added TI-RADS size/category recommendation logic (TR3/TR4/TR5).",
  "",
  "6) Randomized consistency testing",
  "- Implemented randomized test harness for findings/rule consistency.",
  "- Ran 5000 randomized cases; final randomized rule-consistency run passed with zero failures.",
  "",
  "7) Structured hospital-style report generation",
  "- Added Generate Report workflow with patient details, exam details, indication, technique, key measurements, findings, impression, recommendations, additional notes.",
  "- Added formatted report dialog and raw-text tab.",
  "",
  "8) Mock patient and case generation for testing",
  "- Added seeded random mock patients and per-patient random abdomen/thyroid worksheet cases.",
  "- Updated patient selection to auto-load case data and notes.",
  "",
  "9) Documentation added",
  "- WORKSHEET_CHANGES.md",
  "- FDA_ACCURACY_READINESS.md",
  "",
  "10) Files updated",
  "- app/page.tsx",
  "- src/lib/sonoflow-types.ts",
  "- src/lib/report-engine.ts",
  "- src/lib/smart-parser.ts",
  "- src/components/sonoflow/ClinicalWorksheet.tsx",
  "- src/components/sonoflow/ThyroidWorksheet.tsx",
  "- src/components/sonoflow/ReportPreview.tsx",
  "- src/components/sonoflow/StructuredReportDialog.tsx",
  "- scripts/random-findings-validation.ts",
  "- scripts/generate_changelog_docx.py",
  "- WORKSHEET_CHANGES.md",
  "- FDA_ACCURACY_READINESS.md",
  "",
  "Generated by Codex."
)

$escaped = $lines | ForEach-Object { [System.Security.SecurityElement]::Escape($_) }
$paras = ($escaped | ForEach-Object { '<w:p><w:r><w:t xml:space="preserve">' + $_ + '</w:t></w:r></w:p>' }) -join ""
$doc = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>' + $paras + '<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="708" w:footer="708" w:gutter="0"/></w:sectPr></w:body></w:document>'

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText((Join-Path $tmp "[Content_Types].xml"), $contentTypes, $utf8NoBom)
[System.IO.File]::WriteAllText((Join-Path $tmp "_rels\.rels"), $rels, $utf8NoBom)
[System.IO.File]::WriteAllText((Join-Path $tmp "word\document.xml"), $doc, $utf8NoBom)

if (Test-Path $out) {
  Remove-Item $out -Force
}

Compress-Archive -Path (Join-Path $tmp "*") -DestinationPath ($out + ".zip") -Force
Move-Item -Path ($out + ".zip") -Destination $out -Force
Remove-Item $tmp -Recurse -Force

Write-Output $out
